name: Auto Assign
on:
  pull_request:
    types: [opened, reopened, ready_for_review]
jobs:
  auto-assign:
    runs-on: ubuntu-latest
    steps:
      - name: Auto Assign Action
        uses: kentaro-m/auto-assign-action@v2.0.0
        with:
          configuration-path: '.github/workflows/auto_assign.yml'
