name: App releases

on:
  push:
    branches:
      - main  # Solo en la rama 'main'

jobs:
  if_merged:
    if: github.event.pull_request.merged == true
      build:
        runs-on: macos-latest

        steps:
        - name: Checkout code
          uses: actions/checkout@v4
        
        - name: Setup .NET
          uses: actions/setup-dotnet@v4
          with:
            dotnet-version: 9.0.x 

        - name: Select Xcode 16.1
          run: sudo xcode-select -s /Applications/Xcode_16.1.app

        - name: Install workloads for Android, iOS, and Mac Catalyst
          run: |
            dotnet workload install maui-android
            dotnet workload install maui-ios

        - name: Restore dependencies
          run: dotnet restore

        - name: Build Release
          run: dotnet build --configuration Release --no-restore

        - name: Publish Release
          run: |
            mkdir -p ./publish
            dotnet publish --configuration Release --output ./publish
            
        - name: Create GitHub Release
          uses: softprops/action-gh-release@v1
          with:
            files: ./output/*
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
